export const APP = {
    VERSION: "v1"
}

export const DATA_SOURCE = {
    PATIENT_REPOSITORY: "PATIENT_REPOSITORY",
    APPOINTMENT_REPOSITORY: "APPOINTMENT_REPOSITORY",
    SERVICE_REPOSITORY: "SERVICE_REPOSITORY",
    APPOINTMENT_SERVICE_REPOSITORY: "APPOINTMENT_SERVICE_REPOSITORY",
    MEDICAL_AREA_REPOSITORY: "MEDICAL_AREA_REPOSITORY"
}